//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About_tbl
    {
        public int About_ID { get; set; }
        public string About_WhoAreWe { get; set; }
        public string About_WhoAreWe_Two { get; set; }
        public string About_Content { get; set; }
        public string About_Content_Two { get; set; }
        public string About_Mission { get; set; }
        public string About_Mission_Two { get; set; }
        public string About_Vision { get; set; }
        public string About_Vision_Two { get; set; }
        public string About_Career { get; set; }
    }
}
