//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltSlider_tbl
    {
        public int AltSlider_ID { get; set; }
        public Nullable<int> AltSlider_Service_ID { get; set; }
        public Nullable<int> AltSlider_Project_ID { get; set; }
        public string AltSlider_Path { get; set; }
    }
}
