//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands_tbl
    {
        public int Brand_ID { get; set; }
        public string Brand_Content { get; set; }
        public string Brand_Content_Two { get; set; }
        public string Brand_Image { get; set; }
    }
}
