//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yilmazoglugroupDBEntities : DbContext
    {
        public yilmazoglugroupDBEntities()
            : base("name=yilmazoglugroupDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About_tbl> About_tbl { get; set; }
        public virtual DbSet<Projects_tbl> Projects_tbl { get; set; }
        public virtual DbSet<Services_tbl> Services_tbl { get; set; }
        public virtual DbSet<News_tbl> News_tbl { get; set; }
        public virtual DbSet<Brands_tbl> Brands_tbl { get; set; }
        public virtual DbSet<AltSlider_tbl> AltSlider_tbl { get; set; }
        public virtual DbSet<Sliders_tbl> Sliders_tbl { get; set; }
        public virtual DbSet<Cv_tbl> Cv_tbl { get; set; }
        public virtual DbSet<Settings_tbl> Settings_tbl { get; set; }
        public virtual DbSet<Login_tbl> Login_tbl { get; set; }
    }
}
