//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_tbl
    {
        public int Blog_ID { get; set; }
        public string Blog_Image { get; set; }
        public string Blog_Summary { get; set; }
        public string Blog_Summary_Two { get; set; }
        public string Blog_Content { get; set; }
        public string Blog_Content_Two { get; set; }
        public string Blog_Header { get; set; }
        public string Blog_Header_Two { get; set; }
        public Nullable<System.DateTime> Blog_AddDate { get; set; }
    }
}
