//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects_tbl
    {
        public int Project_ID { get; set; }
        public string Project_Image { get; set; }
        public string Project_Content { get; set; }
        public string Project_Content_Two { get; set; }
        public string Project_Summary { get; set; }
        public string Project_Summary_Two { get; set; }
        public Nullable<int> Project_Statu { get; set; }
        public string Project_Country { get; set; }
        public string Project_City { get; set; }
        public string Project_Sector { get; set; }
        public Nullable<System.DateTime> Project_StartDate { get; set; }
        public Nullable<System.DateTime> Project_EndDate { get; set; }
        public Nullable<int> Project_Situation { get; set; }
        public string Project_Header { get; set; }
        public string Project_Header_Two { get; set; }
    }
}
