//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_tbl
    {
        public int Service_ID { get; set; }
        public string Service_Image { get; set; }
        public string Service_Summary { get; set; }
        public string Service_Summary_Two { get; set; }
        public string Service_Content { get; set; }
        public string Service_Content_Two { get; set; }
        public string Service_Header { get; set; }
        public string Service_Header_Two { get; set; }
    }
}
