//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings_tbl
    {
        public int Settings_ID { get; set; }
        public string Settings_Address { get; set; }
        public string Settings_Phone { get; set; }
        public string Settings_Phone_Mobile { get; set; }
        public string Settings_Mail { get; set; }
        public string Settings_Facebook { get; set; }
        public string Settings_Twitter { get; set; }
        public string Settings_Instagram { get; set; }
    }
}
