//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazOgluProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sliders_tbl
    {
        public int Slider_ID { get; set; }
        public Nullable<int> Slider_Service_ID { get; set; }
        public string Slider_Path { get; set; }
    }
}
